// Generated by scripts/generate-custom-images.mjs from data/custom. Do not edit.
// Extra studio exports for the orbit. The caption is the prompt slug from each
// file name; the model is the one that produced it where the name records it.
export type CustomImage = {
	id: string;
	alt: string;
	model: string | null;
	width: number;
	height: number;
};

export const customImages: CustomImage[] = [
	{
		id: '4765dcdc',
		alt: 'Porcelain teacup still life',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '75069fa3',
		alt: 'Desert dune footprints',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'a3e4eb43',
		alt: 'Rain soaked neon alley',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '41109db5',
		alt: 'Runner in a storm',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: 'dd68d009',
		alt: 'Ukiyo e fuji sunset',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '949f9c0e',
		alt: 'Escher staircases in fog',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '4f16e750',
		alt: 'Flying feathers over mountains',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '1e4d85c1',
		alt: 'Cloud staircase',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'b013d807',
		alt: 'Sky pirate airship',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '22ae75dc',
		alt: 'Cyber shrine fox',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'd1464a2c',
		alt: 'Cliffside monastery fog',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '50de6234',
		alt: 'Alpine train viaduct',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'c4dacbb9',
		alt: 'Abandoned observatory',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '1b203e06',
		alt: 'Rice terrace monsoon',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'f189760f',
		alt: 'Ice hotel corridor',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '4051b8cd',
		alt: 'Canyon slot light',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'c578ef7e',
		alt: 'Robot and bonsai',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '3a096369',
		alt: 'Collage city portrait',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '40eb17e1',
		alt: 'Studio squirrel portrait',
		model: 'ssd-1b-lightning',
		width: 1024,
		height: 1024
	},
	{
		id: 'e2254b6c',
		alt: 'Watercolor fox in autumn',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'af86520c',
		alt: 'Aboriginal dot painting river',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '09b9b7bc',
		alt: 'Aboriginal dot painting river',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'd2366438',
		alt: 'Aboriginal dot painting river',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '226927d8',
		alt: 'Escher staircases in fog',
		model: 'ssd-1b',
		width: 768,
		height: 768
	},
	{
		id: 'd5fd51cf',
		alt: 'Chibi mountain hiker',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'ff477acf',
		alt: 'Relaxed minion vacation',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '58740eff',
		alt: 'Relaxed minion vacation',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '525dbcc2',
		alt: 'Flow field gold and purple',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'e5a57842',
		alt: 'Sci fi book cover',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '3d881907',
		alt: 'Sci fi book cover',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '3ef01465',
		alt: 'Makako charcoal study',
		model: 'ssd-1b',
		width: 768,
		height: 768
	},
	{
		id: '5a8727d2',
		alt: 'Merlin oil portrait classical',
		model: 'ssd-1b-lightning',
		width: 1024,
		height: 1024
	},
	{
		id: '46c51269',
		alt: 'Merlin oil portrait classical',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'fbfa5301',
		alt: 'Flying feathers over mountains',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'a1bf8914',
		alt: 'Sky pirate airship',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '4766d165',
		alt: 'Tea spirit portrait',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'a0fd46ac',
		alt: 'Smoke ribbon sculpture',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '4b8543e8',
		alt: 'Smoke ribbon sculpture',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'c4011165',
		alt: 'Woven light threads',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'e1fcb510',
		alt: 'Bioluminescent mangrove',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '8930915b',
		alt: 'Robot and bonsai',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'a07bbc1a',
		alt: 'Ink wash crane',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '6e1c9f47',
		alt: 'Giant pocket watch canyon',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'a560d8d8',
		alt: 'Iridescent oil swirl',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '8451039b',
		alt: 'Synthwave album cover',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'c74e3117',
		alt: 'Cliffside monastery fog',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'cde299e4',
		alt: 'Underwater living room',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '0fb39cd0',
		alt: 'Cyber shrine fox',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '6901b791',
		alt: 'Eco protest poster',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'b2568ec4',
		alt: 'Alpine train viaduct',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '0fe51cef',
		alt: 'Tide pool macro',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'e276b512',
		alt: 'Crystal mage apprentice',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '7b60294e',
		alt: 'Magnetic sand waves',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '3ea9868a',
		alt: 'Fractured porcelain sky',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '9630a3f6',
		alt: 'Abandoned observatory',
		model: 'sdxl-fast',
		width: 1024,
		height: 1024
	},
	{
		id: 'bc7a6959',
		alt: 'Glitch stained glass',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '60dfe89a',
		alt: 'Kitchen alchemy',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '4364ae69',
		alt: 'Orbiting studio desk',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: 'db8c2afa',
		alt: 'High guidance',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '411e0ad8',
		alt: 'High guidance',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '92822fad',
		alt: 'High guidance',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: 'd93fd9a6',
		alt: 'High guidance',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	}
];

export function customSources(image: CustomImage) {
	return {
		src: `/images/custom/${image.id}-480.webp`,
		srcset: `/images/custom/${image.id}-320.webp 320w, /images/custom/${image.id}-480.webp 480w`
	};
}
