// Generated by scripts/generate-making-images.mjs from data/making. Do not edit.
// Gallery wall for the orbit "what people are making" section.
export type MakingImage = {
	id: string;
	alt: string;
	model: string | null;
	width: number;
	height: number;
};

export const makingImages: MakingImage[] = [
	{
		id: '4051b8cd',
		alt: 'Slot canyon sandstone looking up to a blue sky slit',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'c4011165',
		alt: 'Symmetrical neon green and orange filament field',
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '40eb17e1',
		alt: 'Close-up red squirrel portrait',
		model: 'ssd-1b-lightning',
		width: 1024,
		height: 1024
	},
	{
		id: 'e2254b6c',
		alt: 'Watercolor red fox in autumn leaves',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '46c51269',
		alt: 'Classical oil portrait of a white-bearded sage',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '0fe51cef',
		alt: 'Tide pool macro with pink anemones',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '9630a3f6',
		alt: 'Abandoned stone observatory under the Milky Way',
		model: 'sdxl-fast',
		width: 1024,
		height: 1024
	},
	{
		id: '74834694',
		alt: 'Twin golden hourglasses on a starlit shore',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'dbabe82b',
		alt: 'Open door standing alone in a wheat field by the sea',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'dfbc1ddc',
		alt: 'Autumn dragon perched above a mountain lake',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'f4c54d4a',
		alt: 'Geometric gold phoenix rising from red flame',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: '9ed37faf',
		alt: 'Harpist with a glowing harp in a blue canyon',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: '52dcdb6f',
		alt: 'Astronaut beside a golden solar sail over Earth',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: '372573a5',
		alt: 'Ink-wash pine and misty mountain peaks',
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'db8c2afa',
		alt: 'Snowy owl on a snow-dusted branch',
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '3f10ffd0',
		alt: 'White ceramic dragon head, low-angle snarl',
		model: 'sdxl-fast',
		width: 1024,
		height: 1024
	},
	{
		id: 'a0fd46ac',
		alt: 'Floating ribbons of magenta, cyan, and gold smoke',
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'a1bf8914',
		alt: 'Anime sky-pirate airship through cotton-candy clouds',
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	}
];

export function makingSources(image: MakingImage) {
	return {
		src: `/images/making/${image.id}-768.webp`,
		srcset: `/images/making/${image.id}-480.webp 480w, /images/making/${image.id}-768.webp 768w, /images/making/${image.id}-1024.webp 1024w`
	};
}
