// Generated by scripts/generate-making-images.mjs from data/making. Do not edit.
// Gallery wall for the orbit "what people are making" section.
export type MakingImage = {
	id: string;
	alt: string;
	model: string | null;
	width: number;
	height: number;
};

export const makingImages: MakingImage[] = [
	{
		id: '4051b8cd',
		alt: "Studio generation",
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: 'c4011165',
		alt: "Studio generation",
		model: null,
		width: 1024,
		height: 1024
	},
	{
		id: '40eb17e1',
		alt: "Studio squirrel portrait",
		model: 'ssd-1b-lightning',
		width: 1024,
		height: 1024
	},
	{
		id: 'e2254b6c',
		alt: "Watercolor fox in autumn",
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: '46c51269',
		alt: "Merlin oil portrait classical",
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '0fe51cef',
		alt: "Tide pool macro",
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	},
	{
		id: '9630a3f6',
		alt: "Abandoned observatory",
		model: 'sdxl-fast',
		width: 1024,
		height: 1024
	},
	{
		id: '74834694',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'dbabe82b',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'dfbc1ddc',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'f4c54d4a',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: '9ed37faf',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: '52dcdb6f',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: '372573a5',
		alt: "Best 1024 50step",
		model: 'sd35-medium',
		width: 1024,
		height: 1024
	},
	{
		id: 'db8c2afa',
		alt: "High guidance",
		model: 'sdxl-base',
		width: 1024,
		height: 1024
	},
	{
		id: '3f10ffd0',
		alt: "An intimate head on low angle close up p",
		model: 'sdxl-fast',
		width: 1024,
		height: 1024
	},
	{
		id: 'a0fd46ac',
		alt: "Abstract ribbons of colored smoke forming a floa",
		model: 'sdxl-hypersd',
		width: 1024,
		height: 1024
	},
	{
		id: 'a1bf8914',
		alt: "Anime sky pirate airship sailing through cotton",
		model: 'ssd-1b',
		width: 1024,
		height: 1024
	}
];

export function makingSources(image: MakingImage) {
	return {
		src: `/images/making/${image.id}-480.webp`,
		srcset: `/images/making/${image.id}-320.webp 320w, /images/making/${image.id}-480.webp 480w`
	};
}
